### ISSUE TITLE
swagger::ByteArray and string:binary.

### ISSUE THREAD

**Issue by petclemenza** [Metaswitch/swagger-rs#111]
Hi guys,

I am not enirely sure if it's an issue. So, I would like to get your opinion. 

Open API spec says that binary strings are not base64-encoded.
https://swagger.io/specification/
string | byte | base64 encoded characters
string | binary | any sequence of octets

But rust-server codegen uses swagger::ByteArray for both, binary and byte formats.
https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/RustServerCodegen.java#L120-L121

As far as I understand swagger::ByteArray is always base64-encoded. Am I missing something here?

**Comment by mirw** [comment]
Thanks for raising!  I think there's a bug, but I'm not quite sure what the right behavior is...

On the Rust API, I don't think a developer should care whether this data will be serialized as base64 or binary, hence both map to swagger::ByteArray.

I suspect the bug here is that, when serialized to JSON, we serialize as base64 whether the specification specifies `byte` or `binary`.  However, I don't think JSON defines a way of passing raw bytes (e.g. `"` would need to be escaped in some way), so I'm not sure it's really meaningful to specify `binary` for a field in a JSON body.  What do you think?

Binary fields that are included directly as part of the HTTP body (e.g. via a multipart/* encoding) should be encoded correctly (although worth checking that they actually are).

BTW, all active Rust development takes place on the [openapi-generator](https://github.com/OpenAPITools/openapi-generator) fork rather than the swagger-codegen project you refer to.  See the [Q&A](https://github.com/OpenAPITools/openapi-generator/blob/master/docs/qna.md) for reasons.

**Comment by mirw** [comment]
Just noticed https://github.com/OpenAPITools/openapi-generator/issues/3189, which is related.

**Comment by petclemenza** [comment]
Suggested fix to use `Vec<u8>` instead makes sense to me.  I guess it's swagger-rs issue.
Also, it's worth mentioning that JSON is not the only serialization format: e.g. CBOR is binary one.

**Comment by mirw** [comment]
Good point about CBOR... but I don't think openapi-generator for Rust supports that at all!

**Comment by petclemenza** [comment]
Since it uses **serde** for serialization it's actually straightforward to extend that.
